# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b08da25a91fea6c6b10183e7000a28089b9dc037fcaad9714f993da155e047424f39df5ecd1b227cbdd87edcc38a392597bfad407afc971d3f5a34013e4df82

test:
  secret_key_base: 85709067d4e5a13d2554e4b367c7b134cdab2b79fb21ef783506fc07655ed857464c8911b33246c840d1ba9574f83e6636bff17ec3dd3e41c8fd864af76db3f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
